---
name: "Sanity Check"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v4
      -
        name: "Setup Environment"
        run: |
          sudo ./install.sh
