---
name: "Sanity Check"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v4
      -
        name: "Setup Environment"
        run: |
          apt-get update
          apt-get -y install binutils gcc make
          make
